name: Code check

on:
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code check
    if: github.event.pull_request.draft == false
    env:
      SKIP_ENV_VALIDATION: true
      NEXT_TELEMETRY_DISABLED: 1
      DTS_ONLY: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build (packages)
        run: pnpm build --filter="./packages/*"

#      - name: Build api
#        run: |
#          export NODE_OPTIONS=--max_old_space_size=4096
#          pnpm build --filter api
#
#      - name: Build www
#        run: pnpm build --filter www

      - name: Run eslint (packages)
        run: pnpm lint --filter="./packages/*"

      - name: Run prettier
        run: pnpm format:check

      - name: Run typecheck (packages)
        run: pnpm typecheck  --filter="./packages/*"
